import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/page";
import Footer from "@/components/footer/page";
import { Toaster } from "react-hot-toast";
import CartContextProvider from "@/components/Context/CartContext";
import WishContextProvider from "@/components/Context/WishlistContext";
import MySessionProvider from "@/components/MySessionProvider/MySessionProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <MySessionProvider>
        <CartContextProvider>
      <WishContextProvider>
        <Navbar />
        <div className="  bg-linear-to-br from-blue-50 to-blue-200 min-h-150 py-5 px-5">
        <div className=" container mx-auto pb-5">
            {children}
            <Toaster/>
        </div>
        </div>
        <Footer />
      </WishContextProvider>
      </CartContextProvider>
      </MySessionProvider>
      </body>
    </html>
  );
}
